// <auto-generated />
using System;
using Grow.Server.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Grow.Server.Migrations
{
    [DbContext(typeof(GrowDbContext))]
    [Migration("20190307183653_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Grow.Server.Model.Entities.Contest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("FinalEventId");

                    b.Property<int?>("KickoffEventId");

                    b.Property<string>("Language");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Year");

                    b.HasKey("Id");

                    b.HasIndex("FinalEventId");

                    b.HasIndex("KickoffEventId");

                    b.HasIndex("Year");

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int?>("ContestId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<DateTime>("End");

                    b.Property<string>("FacebookLink");

                    b.Property<bool>("HasTimesSet");

                    b.Property<int?>("HeldById");

                    b.Property<bool>("IsMandatory");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<DateTime>("Start");

                    b.Property<int>("Type");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("Visibility");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("HeldById");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AltText");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.JoinEntities.JudgeToContest", b =>
                {
                    b.Property<int>("PersonId");

                    b.Property<int>("ContestId");

                    b.HasKey("PersonId", "ContestId");

                    b.HasIndex("ContestId");

                    b.ToTable("JudgeToContest");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.JoinEntities.MentorToContest", b =>
                {
                    b.Property<int>("PersonId");

                    b.Property<int>("ContestId");

                    b.HasKey("PersonId", "ContestId");

                    b.HasIndex("ContestId");

                    b.ToTable("MentorToContest");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.JoinEntities.OrganizerToContest", b =>
                {
                    b.Property<int>("PersonId");

                    b.Property<int>("ContestId");

                    b.Property<string>("Contribution");

                    b.HasKey("PersonId", "ContestId");

                    b.HasIndex("ContestId");

                    b.ToTable("OrganizerToContest");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.JoinEntities.PartnerToContest", b =>
                {
                    b.Property<int>("PartnerId");

                    b.Property<int>("ContestId");

                    b.HasKey("PartnerId", "ContestId");

                    b.HasIndex("ContestId");

                    b.ToTable("PartnerToContest");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int?>("ImageId");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("Expertise");

                    b.Property<int?>("ImageId");

                    b.Property<string>("JobTitle");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("WebsiteUrl");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.Prize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContestId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int?>("GivenById");

                    b.Property<bool>("IsPublic");

                    b.Property<string>("Name");

                    b.Property<string>("Reward");

                    b.Property<int>("RewardValue");

                    b.Property<int>("Type");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("WinnerId");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("GivenById");

                    b.HasIndex("WinnerId");

                    b.ToTable("Prizes");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActiveSince");

                    b.Property<int?>("ContestId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("FacebookUrl");

                    b.Property<string>("InstagramUrl");

                    b.Property<bool>("IsActive");

                    b.Property<int?>("LogoImageId");

                    b.Property<string>("MembersAsString");

                    b.Property<string>("Name");

                    b.Property<string>("TagLine");

                    b.Property<int?>("TeamPhotoId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("WebsiteUrl");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("LogoImageId");

                    b.HasIndex("TeamPhotoId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.Contest", b =>
                {
                    b.HasOne("Grow.Server.Model.Entities.Event", "FinalEvent")
                        .WithMany()
                        .HasForeignKey("FinalEventId");

                    b.HasOne("Grow.Server.Model.Entities.Event", "KickoffEvent")
                        .WithMany()
                        .HasForeignKey("KickoffEventId");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.Event", b =>
                {
                    b.HasOne("Grow.Server.Model.Entities.Contest", "Contest")
                        .WithMany("Events")
                        .HasForeignKey("ContestId");

                    b.HasOne("Grow.Server.Model.Entities.Partner", "HeldBy")
                        .WithMany()
                        .HasForeignKey("HeldById");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.JoinEntities.JudgeToContest", b =>
                {
                    b.HasOne("Grow.Server.Model.Entities.Contest", "Contest")
                        .WithMany("Judges")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Grow.Server.Model.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.JoinEntities.MentorToContest", b =>
                {
                    b.HasOne("Grow.Server.Model.Entities.Contest", "Contest")
                        .WithMany("Mentors")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Grow.Server.Model.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.JoinEntities.OrganizerToContest", b =>
                {
                    b.HasOne("Grow.Server.Model.Entities.Contest", "Contest")
                        .WithMany("Organizers")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Grow.Server.Model.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.JoinEntities.PartnerToContest", b =>
                {
                    b.HasOne("Grow.Server.Model.Entities.Contest", "Contest")
                        .WithMany("Partners")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Grow.Server.Model.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.Partner", b =>
                {
                    b.HasOne("Grow.Server.Model.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.Person", b =>
                {
                    b.HasOne("Grow.Server.Model.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.Prize", b =>
                {
                    b.HasOne("Grow.Server.Model.Entities.Contest", "Contest")
                        .WithMany("Prizes")
                        .HasForeignKey("ContestId");

                    b.HasOne("Grow.Server.Model.Entities.Partner", "GivenBy")
                        .WithMany()
                        .HasForeignKey("GivenById");

                    b.HasOne("Grow.Server.Model.Entities.Team", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");
                });

            modelBuilder.Entity("Grow.Server.Model.Entities.Team", b =>
                {
                    b.HasOne("Grow.Server.Model.Entities.Contest", "Contest")
                        .WithMany("Teams")
                        .HasForeignKey("ContestId");

                    b.HasOne("Grow.Server.Model.Entities.Image", "LogoImage")
                        .WithMany()
                        .HasForeignKey("LogoImageId");

                    b.HasOne("Grow.Server.Model.Entities.Image", "TeamPhoto")
                        .WithMany()
                        .HasForeignKey("TeamPhotoId");
                });
#pragma warning restore 612, 618
        }
    }
}
